[tool.poetry]
name = "miose-toolkit-common"
version = "0.0.3"
description = "Miose Toolkit 通用模块"
authors = ["KroMiose <li_xiangff@163.com>"]
packages = [{ include = "miose_toolkit_common", from = "src" }]

[tool.poetry.dependencies]
python = "^3.8, <3.11"
aiohttp = "^3.8.6"
ujson = "^5.8.0"
requests = "^2.31.0"
poetry = "^1.6.1"
pydantic = "^2.4.2"
pyyaml = "^6.0.1"

[tool.poetry.scripts]
test = "src.tests:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
